### ISSUE TITLE
IAM Controller - Status message error

### ISSUE THREAD

**Issue by fcosta-td** [aws-controllers-k8s/community#1297]
**Describe the bug**
Roles created with IAM controller despite being created successfully, always show the following status message when describing the object on Kubernetes:

```
Status:
  Ack Resource Metadata:
    Arn:               arn:aws:iam::<REDACTED>:role/role-test-1
    Owner Account ID:  <REDACTED>
    Region:            us-east-1
  Conditions:
    Message:               InvalidInput: Error occurred while validating input. 
                           status code: 400, request id: 38f5f71b-b981-442f-b875-3ee927fdedb5
    Status:                True
    Type:                  ACK.Terminal
    Last Transition Time:  2022-05-18T13:17:33Z
    Message:               Resource synced successfully
    Reason:                resource is in terminal condition
    Status:                True
    Type:                  ACK.ResourceSynced
  Create Date:             2022-05-17T12:26:13Z
  Role ID:                 <REDACTED>
  Role Last Used:
Events:  <none>
```

**Steps to reproduce**
Create a role with IAM Controller, and run `kubectl describe`

**Expected outcome**
Status message without errors.

**Environment**
* Kubernetes version
* Using EKS:  yes (v1.21.9-eks-0d102a7)
* AWS service targeted: IAM

**Comment by RedbackThomson** [comment]
I believe this error has been fixed as part of [`v0.0.14`](https://github.com/aws-controllers-k8s/iam-controller/releases/tag/v0.0.14). Please let me know if that doesn't work.

**Comment by fcosta-td** [comment]
Hi @RedbackThomson,

I've just tested with `v0.0.14` and still getting the same error.
Checking the logs in DEBUG i can see a couple of errors:

```
1.6532938514391167e+09    DEBUG    exporter.field-export-reconciler    error did not need requeue    {"error": "the source resource is not synced yet"}

1.6532938519710267e+09    DEBUG    ackrt    <<< rm.Update    {"account": "<REDACTED>", "role": "", "region": "us-east-1", "kind": "Role", "namespace": "irsa-example", "name": "irsa-example-6cb018c2c483e9ea", "is_adopted": false, "generation": 3, "latest": {}, "error": "resource is in terminal condition"}
```

**Comment by jaypipes** [comment]
@fcosta-td Hi! Definitely there should never be ACK.ResourceSynced=TRUE and ACK.Terminal=TRUE appearing at the same time in a resource's `Status.Conditions` collection, so since that is the case, that's definitely a bug. I will look into that.

It would be super helpful if you provided us the exact YAML you are using for the Role resource, please. Go ahead and redact any sensitive information of course. Thank you!

**Comment by fcosta-td** [comment]
Hi @jaypipes, I get the same error on all roles created with IAM controller (even on the [repo's example](https://github.com/aws-controllers-k8s/iam-controller/blob/main/test/e2e/resources/role_simple.yaml) )

Here's the example reported in this issue:
```
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: irsa-example-6cb018c2c483e9ea
  namespace: default
spec:
  name: irsa-example-6cb018c2c483e9ea
  description: "Teste"
  maxSessionDuration: 3600
  assumeRolePolicyDocument: >
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Federated": "arn:aws:iam::<REDACTED>:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/<REDACTED>"
          },
          "Action": "sts:AssumeRoleWithWebIdentity",
          "Condition": {
            "StringEquals": {
                "oidc.eks.us-east-1.amazonaws.com/id/<REDACTED>:sub": "system:serviceaccount:default:irsa-example-6cb018c2c483e9ea"
            }
          }
        }
      ]
    }
  tags:
    - key: type
      value: role
    - key: test
      value: "1"
```

**Comment by RedbackThomson** [comment]
@fcosta-td I have released `v0.0.15` with the latest fix for tagging causing the invalid input terminal exception - https://github.com/aws-controllers-k8s/iam-controller/releases/tag/v0.0.15

**Comment by fcosta-td** [comment]
Hi @RedbackThomson this latest version fixes the issue.

Here's the output:
```
Status:
  Ack Resource Metadata:
    Arn:               arn:aws:iam::<REDACTED>:role/irsa-example-6cb018c2c483e9ea
    Owner Account ID:  <REDACTED>
    Region:            us-east-1
  Conditions:
    Last Transition Time:  2022-05-25T08:09:58Z
    Status:                True
    Type:                  ACK.ResourceSynced
    Last Transition Time:  2022-05-25T08:09:58Z
    Message:               Late initialization successful
    Reason:                Late initialization successful
    Status:                True
    Type:                  ACK.LateInitialized
  Create Date:             2022-05-25T08:09:10Z
  Role ID:                 <REDACTED>
  Role Last Used:
```
Thanks.
